### ISSUE TITLE
overlays are not supported

### ISSUE THREAD

**Issue by vojeroen** [hartwork/binary-gentoo#34]
I'm just going to leave this here for future reference but I don't have an immediate need for this myself. Might be an interesting enhancement if/when you have the time, or if users are asking for it.

I noticed that overlays are not supported. I can image there will be users that will want to build packages from other sources/overlays.

**Comment by hartwork** [comment]
@vojeroen if neither you nor me need this today, let's not make ticket for things like that: If we can get and keep the issue count at zero (a bit like "inbox zero"), I consider that healthy. I hope it's okay for you if I just close this ticket. Thanks for your understanding.

**Comment by vojeroen** [comment]
Ok, no problem.
