### ISSUE TITLE
cron execution of gentoo-tree-sync fails

### ISSUE THREAD

**Issue by vojeroen** [hartwork/binary-gentoo#45]
Hi,

I'm setting up a cron to daily build new packages, but it isn't working and my logs show the error `the input device is not a TTY`:

```bash
+ gentoo-tree-sync --docker-image gentoo/stage3:amd64 --backup-to /home/portage/portdir-prev /home/portage/portdir
the input device is not a TTY
ERROR: Command "docker run -it --rm -v /home/portage/portdir:/usr/portage:rw -v /home/portage/portdir-prev:/mnt/portage-backup:rw gentoo/stage3:amd64 sh -c 'set -x && rsync --archive --delete --verbose --progress /usr/portage/ /mnt/portage-backup/ && ln -s /usr/portage /var/db/repos/gentoo && env PORTDIR=/usr/portage emerge-webrsync --verbose'" returned non-zero exit status 1.
```

The same command works perfectly when launched from the command line. I believe it is coming from the `-it` arguments that are passed to `docker run`. Is there a specific reason to include these? Otherwise it might be a good idea to remove them.

**Comment by hartwork** [comment]
Hi @vojeroen , long time no see. AFAIR the `-t` TTY needed for ANSI color output and interactive input. Have you checked `gentoo-tree-sync` flag `--non-interactive`? I think if we want to drop a flag here, `-i` would be the one to drop. What do you think?

**Comment by vojeroen** [comment]
I can indeed confirm the `--non-interactive` flags works as expected so cron execution is fine!
