### ISSUE TITLE
Chroot build

### ISSUE THREAD

**Issue by necrose99** [hartwork/binary-gentoo#69]
Im currious if you can do a marginally less isolated build ie pop a stage 3 , and inject libs ie emerge ?x 
or mount local files to the chroot..

Ie debian rpi4 aarch64,  ie for gentoo or rpi4 distro.  

Namely ghc is a royally a pia..  , ie  inject via bind mounts ghc , build gentoo ghc , move over to gentoo on rpi.. via usb , upgrade from then on to hearts content..
Few esoteric forensics tools , that i wish weren't in haskell.. but... 

Sometimes they have ghc-aarch64 starters on gentoo,  but not oftentimes..  of lately .. nor a bin using deb.. to limp the initial compilation along.. 

Even a debian chroot to gentoo in a docker for ghc that spits out ghc packaged would be a plus. 

Anyway a script to do this even as an addition could prove useful..

**Comment by hartwork** [comment]
@necrose99 sorry, but you'll need to spend time writing a proper ticket if you want me to spend time thinking about and it write a reply. Reading that text is a pain and I have no idea what it's about. If this is about something of value, please create a new proper ticket meant to be read by humans. Thank you.

**Comment by necrose99** [comment]
https://stackoverflow.com/questions/23439126/how-to-mount-a-host-directory-in-a-docker-container 
seems docker can be fed local on system dirs.  and or known cp files over as well as volumes 
Distcc i do wish had ghc support else likewise easier  could bind rpi to laptop/servers as well for distcc as is.. 

before 5 recruiters frazzled my head with 10  calls at once ... my apologies , my cell just when you think 5 mins .... RING.. 

docker pull gentoo/stage3:arm64   target/s  (https://github.com/GenPi64) 

https://packages.debian.org/stretch/ghc > gentoo-docker ensure depends  in docker long enough to upgrade/build 
Arm64/aarch64 is not as often smiled  on from on high 

**a plugin** or a **scripted means**   of Dumping a bake'd of GHC for use on Genpi64 aka gentoo since arm64  isn't quite as maintained on gentoo would be of use .. 

**_for a hypothetical  ghc-task-embedded-plug-in_** : ### H(ost)  path on Debian install **Docker**  ie gentoo bind mount path (shorthand) 
were USE="binary " emerge dev-lang/ghc isnt available ie arm64/riscv etc 

```
H:/usr/lib/ghc/ Docker:/usr/lib/ghc/

H:/var/lib/ghc/package.conf.d/ Docker:/var/lib/ghc/package.conf.d

H: /usr/share/doc/ghc/   Docker:/usr/share/doc/ghc/

H: /usr/share/lintian/overrides/ Docker:/usr/share/lintian/overrides/

H: /usr/share/man/man1/ghc  Docker:/usr/share/man/man1/ghc  

H: /usr/lib/ghc/ Docker: /usr/lib/ghc/

_**cp H: /usr/bin/[ghc*,runhaskell,haddock,hsc2hs,hpc,hp2ps}  Docker:/usr/bin/**_ 

**emerge ghc depends ...**  in docker 

USE="elfutils ghcmakebinary gmp numa " emerge dev-lang/ghc    or simular use/s cp  to mount usb wala.. 
```
emerge on rpi gentoo as normal , profit...

**Comment by hartwork** [comment]
@necrose99 you and I do not seem to speak the same language. Let's stop. Thank you.

**Comment by necrose99** [comment]
- in simple terms:  / bullet points : 

**gentoo-build – Builds a Gentoo package with Docker isolation**  _OK you   got my attention_ .... 
_especially for perhaps USEFUL embedded hardware ?_  having Gentoo on RPI4 can be useful .

- **A:** basically invoke *gentoo-build  , 
- ** if necessary/required   with some customized options**  ie mount/expose host ghc to gentoo-build::Docker.. 
 
- example https://raspi.debian.net/daily-images/  + Docker + gentoo-build @aarch64/arm64 

- **B:** dev-lang/ghc  for  **ARM64** is the desired package, among others, esp..  
- 2019 since gentoo has had a valid ARM64-Binary option :-(  , trying to build this package on arm64 is a royal pain normally... 

- **C:**  dose : gentoo-build cross-compile , ?  if so then  ###problem hopefully --->  solved ### 
- great can get things done... 

**D:** or would i need to rig some sort of Frankenstein -helper/wrapper script ?  for this one .... ?  copy bind mount gentoo-build-docker to host paths of ghc to get compile done ... 


**End Goal : dev-lang/ghc , and or other useful Arm64 packages**  


references: 
https://docs.docker.com/storage/bind-mounts/ 

[pypi/fchroot ](https://pypi.org/project/fchroot/)

**Comment by hartwork** [comment]
I insist on stop. Thank you.
