### ISSUE TITLE
Kubler Comparison

### ISSUE THREAD

**Issue by berney** [hartwork/binary-gentoo#79]
What is the differences, and pros/cons of binary-gentoo vs using [kubler ](https://github.com/edannenberg/kubler) to build binary packages?

Kubler is designed to build docker images, it builds them inside docker containers (clean), and will keep the binary packages cached on the host file system. It requires bash4 and docker.

I raised same thing on Kubler's end https://github.com/edannenberg/kubler/issues/207

**Comment by hartwork** [comment]
Hi @berney, I have no prrior experience with Kubler and I'm not sure I have realistic full picture from their readme now. My impression is:

- Kubler seems focused on Docker images while binary-gentoo is focused on Gentoo packages. (I use binary-gentoo myself to build Gentoo packages on a Fedora host for a Gentoo notebook of mine. It can also be use while developing ebuilds on the Gentoo host, locally.)
- Kubler is Bash, binary-gentoo is Python 3.

I won't try to talk you into binary-gentoo. If Kubler works for you, I'm happy for you and Kubler.
If you have more in-depth questions about binary-gentoo, a quick voice call is an option to me most days, if that would help.

Best, Sebastian

**Comment by hartwork** [comment]
Closing, please reach out via e-mail if you have an questions beyond my reply above.
